/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'api-klienti': ApiKlientiAuthOperations;
  };
  blocks: {};
  collections: {
    stranky: Stranky;
    prispevky: Prispevky;
    katalog: Katalog;
    udalosti: Udalosti;
    kategorie: Kategorie;
    media: Media;
    subory: Subory;
    navigacia: Navigacia;
    'nastavenia-webu': NastaveniaWebu;
    presmerovania: Presmerovania;
    formulare: Formulare;
    odpovede: Odpovede;
    zaznamy: Zaznamy;
    projekty: Projekty;
    users: User;
    'api-klienti': ApiKlienti;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    stranky: StrankySelect<false> | StrankySelect<true>;
    prispevky: PrispevkySelect<false> | PrispevkySelect<true>;
    katalog: KatalogSelect<false> | KatalogSelect<true>;
    udalosti: UdalostiSelect<false> | UdalostiSelect<true>;
    kategorie: KategorieSelect<false> | KategorieSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subory: SuborySelect<false> | SuborySelect<true>;
    navigacia: NavigaciaSelect<false> | NavigaciaSelect<true>;
    'nastavenia-webu': NastaveniaWebuSelect<false> | NastaveniaWebuSelect<true>;
    presmerovania: PresmerovaniaSelect<false> | PresmerovaniaSelect<true>;
    formulare: FormulareSelect<false> | FormulareSelect<true>;
    odpovede: OdpovedeSelect<false> | OdpovedeSelect<true>;
    zaznamy: ZaznamySelect<false> | ZaznamySelect<true>;
    projekty: ProjektySelect<false> | ProjektySelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'api-klienti': ApiKlientiSelect<false> | ApiKlientiSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | ApiKlienti;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ApiKlientiAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Podstránky webu poskladané z blokov. Web si ich ťahá cez API podľa cesty.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stranky".
 */
export interface Stranky {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  nazov: string;
  /**
   * Napr. „/“ pre domov alebo „/o-nas/tim“ pre podstránku.
   */
  cesta: string;
  /**
   * Dve–tri vety do výpisu a do náhľadu odkazu. Nepovinné.
   */
  perex?: string | null;
  /**
   * Bloky idú na webe zhora nadol v tomto poradí. Ťahaním ich prehodíš.
   */
  bloky?:
    | (
        | BlokHero
        | BlokText
        | BlokObrazok
        | BlokGaleria
        | BlokVypis
        | BlokDlazdice
        | BlokCta
        | BlokFaq
        | BlokFormular
        | BlokVideo
        | BlokKod
        | BlokOddelovac
      )[]
    | null;
  /**
   * Čo o stránke ukáže Google a náhľad odkazu na sieťach. Prázdne polia sa dopĺňajú z obsahu.
   */
  seo?: {
    /**
     * Do 60 znakov. Prázdne = názov záznamu.
     */
    titulok?: string | null;
    /**
     * Do 160 znakov. Prázdne = perex záznamu.
     */
    popis?: string | null;
    /**
     * Ukáže sa, keď niekto vloží odkaz na Facebook alebo do správy.
     */
    obrazok?: (number | null) | Media;
    neindexovat?: boolean | null;
  };
  /**
   * Doplní sa automaticky pri založení záznamu.
   */
  vytvoril?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Weby napojené na túto administráciu. Každý záznam v systéme patrí práve jednému z nich.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projekty".
 */
export interface Projekty {
  id: number;
  /**
   * Ako sa web volá v administrácii.
   */
  nazov: string;
  /**
   * Pozastavený a archivovaný projekt prestane cez API vydávať obsah. V administrácii ostáva.
   */
  stav: 'aktivny' | 'vystavba' | 'pozastaveny' | 'archiv';
  /**
   * Používa sa v adrese API: /api/web/<kód>/stranky. Krátko, bez diakritiky, nemeniť po nasadení.
   */
  kod: string;
  /**
   * Pre koho web je, čo na ňom beží, na čo si dať pozor.
   */
  popis?: string | null;
  /**
   * Napr. https://vinaren.zjav.sk — aj s protokolom.
   */
  domenaHlavna?: string | null;
  /**
   * Vercel náhľady, www varianta, staré domény so 301.
   */
  domeny?:
    | {
        /**
         * https://nieco.vercel.app alebo http://localhost:3001
         */
        adresa: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Zapnuté: zverejnený obsah si stiahne ktokoľvek z povolených domén — to je pre bežný verejný web správne. Vypnuté: každá požiadavka musí mať API kľúč.
   */
  verejneCitanie?: boolean | null;
  /**
   * Po každej zmene obsahu sem hub pošle POST, aby si web zahodil vyrenderovanú kópiu. Napr. https://web.sk/api/revalidate
   */
  revalidateUrl?: string | null;
  /**
   * Pošle sa v hlavičke x-hub-secret. Web si ním overí, že požiadavka je naozaj z hubu.
   */
  revalidateSecret?: string | null;
  /**
   * Odlíši projekt v prepínači a na nástenke. Hex, napr. #2f6f4e.
   */
  farba?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokHero".
 */
export interface BlokHero {
  nadpis: string;
  podnadpis?: string | null;
  pozadie?: (number | null) | Media;
  varianta?: ('plny' | 'pas' | 'split') | null;
  tlacidla?:
    | {
        text: string;
        /**
         * Napr. /kontakt alebo https://…
         */
        odkaz: string;
        styl?: ('hlavne' | 'vedlajsie' | 'odkaz') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Fotky pre tento projekt. Dajú sa vybrať všade, kde web zobrazuje obrázok.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  /**
   * Čo je na fotke, jednou vetou. Číta ju čítačka obrazovky aj Google.
   */
  alt: string;
  /**
   * Nepovinné. Web ho zobrazí pod obrázkom, ak s ním počíta.
   */
  popisok?: string | null;
  /**
   * Doplní sa automaticky pri založení záznamu.
   */
  vytvoril?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    nahlad?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    karta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobil?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Kto sa dostane do administrácie a ku ktorým projektom. Prístup sa prideľuje po projektoch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Zobrazuje sa pri záznamoch, ktoré človek vytvoril.
   */
  meno: string;
  /**
   * Vidí a mení všetky projekty vrátane zakladania nových. Prideliť to smie len iný master.
   */
  master?: boolean | null;
  /**
   * Vypnuté: človek sa neprihlási a stratí prístup všade.
   */
  aktivny?: boolean | null;
  /**
   * Ku ktorým webom sa človek dostane a čo tam smie. · Správca — všetok obsah projektu, nastavenia webu, navigácia, presmerovania a pozývanie ľudí k projektu. · Editor — vytvára, upravuje, zverejňuje a maže obsah. Nastavenia webu nevidí. · Autor — píše a upravuje výhradne vlastné záznamy a nesmie ich zverejniť. · Pozorovateľ — obsah len číta, nič nemení.
   */
  pristupy?:
    | {
        projekt: number | Projekty;
        rola: 'spravca' | 'editor' | 'autor' | 'pozorovatel';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokText".
 */
export interface BlokText {
  nadpis?: string | null;
  obsah: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sirka?: ('uzka' | 'siroka') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokObrazok".
 */
export interface BlokObrazok {
  obrazok: number | Media;
  popisok?: string | null;
  sirka?: ('obsah' | 'plna') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'obrazok';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokGaleria".
 */
export interface BlokGaleria {
  nadpis?: string | null;
  fotky: (number | Media)[];
  rozlozenie?: ('mriezka' | 'pas' | 'mozaika') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galeria';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokVypis".
 */
export interface BlokVypis {
  nadpis?: string | null;
  /**
   * Blok si obsah dotiahne sám pri každom načítaní — nie je to zoznam, ktorý treba ručne dopĺňať.
   */
  zdroj: 'prispevky' | 'katalog' | 'udalosti';
  /**
   * Prázdne = všetko.
   */
  kategoria?: (number | null) | Kategorie;
  pocet?: number | null;
  rozlozenie?: ('karty' | 'zoznam' | 'kolotoc') | null;
  odkazNaVsetko?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vypis';
}
/**
 * Triedenie príspevkov, katalógu a udalostí.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kategorie".
 */
export interface Kategorie {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  nazov: string;
  /**
   * Časť adresy za lomítkom. Doplní sa z názvu; keď je záznam vonku, radšej ju už nemeň.
   */
  slug: string;
  /**
   * Kde sa kategória ponúkne vo výbere.
   */
  pre?: ('prispevky' | 'katalog' | 'udalosti')[] | null;
  popis?: string | null;
  /**
   * Nižšie číslo je vyššie vo výpise. Rovnaké čísla radí dátum.
   */
  poradie?: number | null;
  /**
   * Doplní sa automaticky pri založení záznamu.
   */
  vytvoril?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokDlazdice".
 */
export interface BlokDlazdice {
  nadpis?: string | null;
  polozky?:
    | {
        nadpis: string;
        text?: string | null;
        ikona?: (number | null) | Media;
        odkaz?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dlazdice';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokCta".
 */
export interface BlokCta {
  nadpis: string;
  text?: string | null;
  tlacidla?:
    | {
        text: string;
        /**
         * Napr. /kontakt alebo https://…
         */
        odkaz: string;
        styl?: ('hlavne' | 'vedlajsie' | 'odkaz') | null;
        id?: string | null;
      }[]
    | null;
  varianta?: ('pas' | 'karta') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokFaq".
 */
export interface BlokFaq {
  nadpis?: string | null;
  otazky?:
    | {
        otazka: string;
        odpoved: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokFormular".
 */
export interface BlokFormular {
  nadpis?: string | null;
  text?: string | null;
  formular: number | Formulare;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formular';
}
/**
 * Kontaktné, rezervačné a dopytové formuláre webu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formulare".
 */
export interface Formulare {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  nazov: string;
  /**
   * Časť adresy za lomítkom. Doplní sa z názvu; keď je záznam vonku, radšej ju už nemeň.
   */
  slug: string;
  /**
   * Poradie tu je poradím na webe.
   */
  polia?:
    | {
        /**
         * Čo do neho človek napíše, napr. „Tvoje meno“.
         */
        popis: string;
        /**
         * Pod týmto názvom hodnota príde a uloží sa. Bez diakritiky.
         */
        kluc: string;
        typ: 'text' | 'textarea' | 'email' | 'tel' | 'cislo' | 'datum' | 'vyber' | 'zaskrtnutie' | 'suhlas';
        povinne?: boolean | null;
        napoveda?: string | null;
        moznosti?:
          | {
              hodnota: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  textTlacidla?: string | null;
  spravaPoOdoslani?: string | null;
  /**
   * Keď je vyplnené, správa sa nezobrazí.
   */
  presmerovanie?: string | null;
  prijemcovia?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Prázdne = „Nová odpoveď z formulára <názov>“.
   */
  predmet?: string | null;
  /**
   * Použije sa prvé pole typu E-mail.
   */
  potvrdenieOdosielatelovi?: boolean | null;
  textPotvrdenia?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokVideo".
 */
export interface BlokVideo {
  nadpis?: string | null;
  /**
   * YouTube, Vimeo alebo priamy odkaz na .mp4.
   */
  adresa?: string | null;
  /**
   * Použije sa, keď je odkaz prázdny.
   */
  subor?: (number | null) | Subory;
  nahlad?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * PDF, dokumenty a videá na stiahnutie alebo vloženie do stránky.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subory".
 */
export interface Subory {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  /**
   * Ako sa súbor volá na webe, napr. „Jedálny lístok 2026“.
   */
  nazov: string;
  /**
   * Doplní sa automaticky pri založení záznamu.
   */
  vytvoril?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokKod".
 */
export interface BlokKod {
  /**
   * Rezervačný widget, mapa, prehrávač. Vkladaj len kód zo zdroja, ktorému veríš — beží na webe návštevníka.
   */
  kod: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'kod';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokOddelovac".
 */
export interface BlokOddelovac {
  velkost?: ('mala' | 'stredna' | 'velka') | null;
  ciara?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'oddelovac';
}
/**
 * Novinky a články. Vo výpise sa radia od najnovšieho.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prispevky".
 */
export interface Prispevky {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  nazov: string;
  /**
   * Časť adresy za lomítkom. Doplní sa z názvu; keď je záznam vonku, radšej ju už nemeň.
   */
  slug: string;
  datum: string;
  /**
   * Prázdne = web meno autora neukáže.
   */
  autorText?: string | null;
  /**
   * Dve–tri vety do výpisu a do náhľadu odkazu. Nepovinné.
   */
  perex?: string | null;
  obrazok?: (number | null) | Media;
  kategorie?: (number | Kategorie)[] | null;
  obsah?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Galéria, výzva k akcii, formulár — čokoľvek pod textom. Nepovinné.
   */
  bloky?:
    | (
        | BlokHero
        | BlokText
        | BlokObrazok
        | BlokGaleria
        | BlokVypis
        | BlokDlazdice
        | BlokCta
        | BlokFaq
        | BlokFormular
        | BlokVideo
        | BlokKod
        | BlokOddelovac
      )[]
    | null;
  odporucany?: boolean | null;
  /**
   * Čo o stránke ukáže Google a náhľad odkazu na sieťach. Prázdne polia sa dopĺňajú z obsahu.
   */
  seo?: {
    /**
     * Do 60 znakov. Prázdne = názov záznamu.
     */
    titulok?: string | null;
    /**
     * Do 160 znakov. Prázdne = perex záznamu.
     */
    popis?: string | null;
    /**
     * Ukáže sa, keď niekto vloží odkaz na Facebook alebo do správy.
     */
    obrazok?: (number | null) | Media;
    neindexovat?: boolean | null;
  };
  /**
   * Doplní sa automaticky pri založení záznamu.
   */
  vytvoril?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ponuka, cenník, produkty alebo služby — čokoľvek, čo má názov a cenu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "katalog".
 */
export interface Katalog {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  nazov: string;
  /**
   * Časť adresy za lomítkom. Doplní sa z názvu; keď je záznam vonku, radšej ju už nemeň.
   */
  slug: string;
  /**
   * Dve–tri vety do výpisu a do náhľadu odkazu. Nepovinné.
   */
  perex?: string | null;
  /**
   * Napr. „5 €“, „od 12 €“ alebo „na dopyt“. Prázdne sa nezobrazí.
   */
  cena?: string | null;
  /**
   * Nepovinné. Použije sa na zoradenie a filtrovanie podľa ceny.
   */
  cenaCislo?: number | null;
  /**
   * Napr. „0,1 l“, „ks“, „noc“.
   */
  jednotka?: string | null;
  kategoria?: (number | null) | Kategorie;
  obrazok?: (number | null) | Media;
  galeria?: (number | Media)[] | null;
  popis?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Dvojice názov – hodnota: Ročník / 2021, Kapacita / 4 osoby, Alergény / 1, 7.
   */
  vlastnosti?:
    | {
        nazov: string;
        hodnota: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vypnuté: web ju ukáže ako nedostupnú alebo skryje.
   */
  dostupne?: boolean | null;
  odporucane?: boolean | null;
  /**
   * Nižšie číslo je vyššie vo výpise. Rovnaké čísla radí dátum.
   */
  poradie?: number | null;
  /**
   * Čo o stránke ukáže Google a náhľad odkazu na sieťach. Prázdne polia sa dopĺňajú z obsahu.
   */
  seo?: {
    /**
     * Do 60 znakov. Prázdne = názov záznamu.
     */
    titulok?: string | null;
    /**
     * Do 160 znakov. Prázdne = perex záznamu.
     */
    popis?: string | null;
    /**
     * Ukáže sa, keď niekto vloží odkaz na Facebook alebo do správy.
     */
    obrazok?: (number | null) | Media;
    neindexovat?: boolean | null;
  };
  /**
   * Doplní sa automaticky pri založení záznamu.
   */
  vytvoril?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Akcie, ochutnávky, kurzy a podujatia.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "udalosti".
 */
export interface Udalosti {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  nazov: string;
  /**
   * Časť adresy za lomítkom. Doplní sa z názvu; keď je záznam vonku, radšej ju už nemeň.
   */
  slug: string;
  /**
   * Dve–tri vety do výpisu a do náhľadu odkazu. Nepovinné.
   */
  perex?: string | null;
  /**
   * Prázdne pri stálej ponuke bez termínu.
   */
  datum?: string | null;
  /**
   * Napr. 19:00
   */
  cas?: string | null;
  /**
   * Použije sa, keď je dátum prázdny. Napr. „Na objednávku“.
   */
  terminText?: string | null;
  miesto?: string | null;
  /**
   * Napr. „5 €“ alebo „Vstup voľný“.
   */
  vstupne?: string | null;
  obrazok?: (number | null) | Media;
  kategoria?: (number | null) | Kategorie;
  popis?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  odkazNaVstupenky?: string | null;
  odporucana?: boolean | null;
  /**
   * Čo o stránke ukáže Google a náhľad odkazu na sieťach. Prázdne polia sa dopĺňajú z obsahu.
   */
  seo?: {
    /**
     * Do 60 znakov. Prázdne = názov záznamu.
     */
    titulok?: string | null;
    /**
     * Do 160 znakov. Prázdne = perex záznamu.
     */
    popis?: string | null;
    /**
     * Ukáže sa, keď niekto vloží odkaz na Facebook alebo do správy.
     */
    obrazok?: (number | null) | Media;
    neindexovat?: boolean | null;
  };
  /**
   * Doplní sa automaticky pri založení záznamu.
   */
  vytvoril?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Odkazy v hlavičke, pätičke a vedľajších zoznamoch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigacia".
 */
export interface Navigacia {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  /**
   * Len pre orientáciu, napr. „Hlavné menu“.
   */
  nazov: string;
  /**
   * Podľa toho si ho web nájde.
   */
  umiestnenie: 'hlavicka' | 'paticka' | 'vedlajsie';
  polozky?:
    | {
        text: string;
        typ: 'stranka' | 'adresa';
        novaKarta?: boolean | null;
        stranka?: (number | null) | Stranky;
        /**
         * Napr. /kontakt, https://instagram.com/… alebo tel:+421…
         */
        adresa?: string | null;
        podpolozky?:
          | {
              text: string;
              typ: 'stranka' | 'adresa';
              novaKarta?: boolean | null;
              stranka?: (number | null) | Stranky;
              /**
               * Napr. /kontakt, https://instagram.com/… alebo tel:+421…
               */
              adresa?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Identita webu, kontakty, siete, meranie a právne texty.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nastavenia-webu".
 */
export interface NastaveniaWebu {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  nazovWebu: string;
  /**
   * Krátko, napr. „Vináreň a wine bar v Trstenej“.
   */
  podtitul?: string | null;
  /**
   * Použije sa ako predvolený popis vo vyhľadávaní.
   */
  popisWebu?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  obrazokZdielania?: (number | null) | Media;
  /**
   * Hex, napr. #2f6f4e.
   */
  farbaHlavna?: string | null;
  farbaDoplnkova?: string | null;
  email?: string | null;
  telefon?: string | null;
  adresa?: string | null;
  /**
   * Odkaz na Google Maps alebo embed adresa.
   */
  mapa?: string | null;
  hodiny?:
    | {
        /**
         * Napr. Pondelok – Štvrtok
         */
        dni: string;
        /**
         * Napr. 16:00 – 22:00 alebo Zatvorené
         */
        cas: string;
        id?: string | null;
      }[]
    | null;
  firemneUdaje?: {
    nazovFirmy?: string | null;
    ico?: string | null;
    dic?: string | null;
    sidlo?: string | null;
  };
  siete?:
    | {
        siet: 'instagram' | 'facebook' | 'tiktok' | 'youtube' | 'linkedin' | 'ine';
        adresa: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Napr. G-XXXXXXX alebo GTM-XXXXXX.
   */
  analytics?: string | null;
  pixel?: string | null;
  cookieLista?: boolean | null;
  /**
   * Prázdne = web použije vlastné predvolené znenie.
   */
  cookieText?: string | null;
  ochranaUdajov?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  obchodnePodmienky?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stará adresa → nová adresa. Web si ich ťahá pri štarte.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presmerovania".
 */
export interface Presmerovania {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  /**
   * Cesta na webe, napr. /stara-stranka
   */
  zo: string;
  /**
   * Cesta alebo celá adresa vrátane https://
   */
  na: string;
  /**
   * Vypnuté = dočasné (307). Trvalé si zapamätá aj prehliadač.
   */
  trvale?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Odoslané formuláre z napojených webov.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "odpovede".
 */
export interface Odpovede {
  id: number;
  projekt: number | Projekty;
  formular: number | Formulare;
  /**
   * Prvé vyplnené pole — aby bolo v zozname vidieť, o čo ide.
   */
  suhrn?: string | null;
  udaje?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  stav?: ('nove' | 'vybavene' | 'spam') | null;
  zdroj?: string | null;
  /**
   * Vidí ju len obsluha, nikam sa neposiela.
   */
  poznamka?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * História zmien obsahu naprieč projektmi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zaznamy".
 */
export interface Zaznamy {
  id: number;
  projekt: number | Projekty;
  akcia?: ('vytvorenie' | 'uprava' | 'zverejnenie' | 'zmazanie') | null;
  kolekcia?: string | null;
  nazov?: string | null;
  kto?: (number | null) | User;
  ktoPopis?: string | null;
  zaznamId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kľúče, ktorými si napojené weby ťahajú obsah. Jeden kľúč = jeden projekt, len na čítanie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-klienti".
 */
export interface ApiKlienti {
  id: number;
  /**
   * Web, ktorému tento záznam patrí. Mimo neho ho nikto neuvidí.
   */
  projekt: number | Projekty;
  /**
   * Napr. „Produkčný web“ alebo „Náhľad na Verceli“.
   */
  nazov: string;
  /**
   * Vypnuté: kľúč okamžite prestane fungovať, ale ostane zapísaný.
   */
  aktivny?: boolean | null;
  /**
   * Kde je kľúč nasadený, kto ho dostal, kedy ho vymeniť.
   */
  poznamka?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'api-klienti';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'stranky';
        value: number | Stranky;
      } | null)
    | ({
        relationTo: 'prispevky';
        value: number | Prispevky;
      } | null)
    | ({
        relationTo: 'katalog';
        value: number | Katalog;
      } | null)
    | ({
        relationTo: 'udalosti';
        value: number | Udalosti;
      } | null)
    | ({
        relationTo: 'kategorie';
        value: number | Kategorie;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subory';
        value: number | Subory;
      } | null)
    | ({
        relationTo: 'navigacia';
        value: number | Navigacia;
      } | null)
    | ({
        relationTo: 'nastavenia-webu';
        value: number | NastaveniaWebu;
      } | null)
    | ({
        relationTo: 'presmerovania';
        value: number | Presmerovania;
      } | null)
    | ({
        relationTo: 'formulare';
        value: number | Formulare;
      } | null)
    | ({
        relationTo: 'odpovede';
        value: number | Odpovede;
      } | null)
    | ({
        relationTo: 'zaznamy';
        value: number | Zaznamy;
      } | null)
    | ({
        relationTo: 'projekty';
        value: number | Projekty;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'api-klienti';
        value: number | ApiKlienti;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'api-klienti';
        value: number | ApiKlienti;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'api-klienti';
        value: number | ApiKlienti;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stranky_select".
 */
export interface StrankySelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  cesta?: T;
  perex?: T;
  bloky?:
    | T
    | {
        hero?: T | BlokHeroSelect<T>;
        text?: T | BlokTextSelect<T>;
        obrazok?: T | BlokObrazokSelect<T>;
        galeria?: T | BlokGaleriaSelect<T>;
        vypis?: T | BlokVypisSelect<T>;
        dlazdice?: T | BlokDlazdiceSelect<T>;
        cta?: T | BlokCtaSelect<T>;
        faq?: T | BlokFaqSelect<T>;
        formular?: T | BlokFormularSelect<T>;
        video?: T | BlokVideoSelect<T>;
        kod?: T | BlokKodSelect<T>;
        oddelovac?: T | BlokOddelovacSelect<T>;
      };
  seo?:
    | T
    | {
        titulok?: T;
        popis?: T;
        obrazok?: T;
        neindexovat?: T;
      };
  vytvoril?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokHero_select".
 */
export interface BlokHeroSelect<T extends boolean = true> {
  nadpis?: T;
  podnadpis?: T;
  pozadie?: T;
  varianta?: T;
  tlacidla?:
    | T
    | {
        text?: T;
        odkaz?: T;
        styl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokText_select".
 */
export interface BlokTextSelect<T extends boolean = true> {
  nadpis?: T;
  obsah?: T;
  sirka?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokObrazok_select".
 */
export interface BlokObrazokSelect<T extends boolean = true> {
  obrazok?: T;
  popisok?: T;
  sirka?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokGaleria_select".
 */
export interface BlokGaleriaSelect<T extends boolean = true> {
  nadpis?: T;
  fotky?: T;
  rozlozenie?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokVypis_select".
 */
export interface BlokVypisSelect<T extends boolean = true> {
  nadpis?: T;
  zdroj?: T;
  kategoria?: T;
  pocet?: T;
  rozlozenie?: T;
  odkazNaVsetko?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokDlazdice_select".
 */
export interface BlokDlazdiceSelect<T extends boolean = true> {
  nadpis?: T;
  polozky?:
    | T
    | {
        nadpis?: T;
        text?: T;
        ikona?: T;
        odkaz?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokCta_select".
 */
export interface BlokCtaSelect<T extends boolean = true> {
  nadpis?: T;
  text?: T;
  tlacidla?:
    | T
    | {
        text?: T;
        odkaz?: T;
        styl?: T;
        id?: T;
      };
  varianta?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokFaq_select".
 */
export interface BlokFaqSelect<T extends boolean = true> {
  nadpis?: T;
  otazky?:
    | T
    | {
        otazka?: T;
        odpoved?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokFormular_select".
 */
export interface BlokFormularSelect<T extends boolean = true> {
  nadpis?: T;
  text?: T;
  formular?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokVideo_select".
 */
export interface BlokVideoSelect<T extends boolean = true> {
  nadpis?: T;
  adresa?: T;
  subor?: T;
  nahlad?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokKod_select".
 */
export interface BlokKodSelect<T extends boolean = true> {
  kod?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlokOddelovac_select".
 */
export interface BlokOddelovacSelect<T extends boolean = true> {
  velkost?: T;
  ciara?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prispevky_select".
 */
export interface PrispevkySelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  slug?: T;
  datum?: T;
  autorText?: T;
  perex?: T;
  obrazok?: T;
  kategorie?: T;
  obsah?: T;
  bloky?:
    | T
    | {
        hero?: T | BlokHeroSelect<T>;
        text?: T | BlokTextSelect<T>;
        obrazok?: T | BlokObrazokSelect<T>;
        galeria?: T | BlokGaleriaSelect<T>;
        vypis?: T | BlokVypisSelect<T>;
        dlazdice?: T | BlokDlazdiceSelect<T>;
        cta?: T | BlokCtaSelect<T>;
        faq?: T | BlokFaqSelect<T>;
        formular?: T | BlokFormularSelect<T>;
        video?: T | BlokVideoSelect<T>;
        kod?: T | BlokKodSelect<T>;
        oddelovac?: T | BlokOddelovacSelect<T>;
      };
  odporucany?: T;
  seo?:
    | T
    | {
        titulok?: T;
        popis?: T;
        obrazok?: T;
        neindexovat?: T;
      };
  vytvoril?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "katalog_select".
 */
export interface KatalogSelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  slug?: T;
  perex?: T;
  cena?: T;
  cenaCislo?: T;
  jednotka?: T;
  kategoria?: T;
  obrazok?: T;
  galeria?: T;
  popis?: T;
  vlastnosti?:
    | T
    | {
        nazov?: T;
        hodnota?: T;
        id?: T;
      };
  dostupne?: T;
  odporucane?: T;
  poradie?: T;
  seo?:
    | T
    | {
        titulok?: T;
        popis?: T;
        obrazok?: T;
        neindexovat?: T;
      };
  vytvoril?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "udalosti_select".
 */
export interface UdalostiSelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  slug?: T;
  perex?: T;
  datum?: T;
  cas?: T;
  terminText?: T;
  miesto?: T;
  vstupne?: T;
  obrazok?: T;
  kategoria?: T;
  popis?: T;
  odkazNaVstupenky?: T;
  odporucana?: T;
  seo?:
    | T
    | {
        titulok?: T;
        popis?: T;
        obrazok?: T;
        neindexovat?: T;
      };
  vytvoril?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kategorie_select".
 */
export interface KategorieSelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  slug?: T;
  pre?: T;
  popis?: T;
  poradie?: T;
  vytvoril?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  projekt?: T;
  alt?: T;
  popisok?: T;
  vytvoril?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        nahlad?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        karta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobil?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subory_select".
 */
export interface SuborySelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  vytvoril?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigacia_select".
 */
export interface NavigaciaSelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  umiestnenie?: T;
  polozky?:
    | T
    | {
        text?: T;
        typ?: T;
        novaKarta?: T;
        stranka?: T;
        adresa?: T;
        podpolozky?:
          | T
          | {
              text?: T;
              typ?: T;
              novaKarta?: T;
              stranka?: T;
              adresa?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nastavenia-webu_select".
 */
export interface NastaveniaWebuSelect<T extends boolean = true> {
  projekt?: T;
  nazovWebu?: T;
  podtitul?: T;
  popisWebu?: T;
  logo?: T;
  favicon?: T;
  obrazokZdielania?: T;
  farbaHlavna?: T;
  farbaDoplnkova?: T;
  email?: T;
  telefon?: T;
  adresa?: T;
  mapa?: T;
  hodiny?:
    | T
    | {
        dni?: T;
        cas?: T;
        id?: T;
      };
  firemneUdaje?:
    | T
    | {
        nazovFirmy?: T;
        ico?: T;
        dic?: T;
        sidlo?: T;
      };
  siete?:
    | T
    | {
        siet?: T;
        adresa?: T;
        id?: T;
      };
  analytics?: T;
  pixel?: T;
  cookieLista?: T;
  cookieText?: T;
  ochranaUdajov?: T;
  obchodnePodmienky?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presmerovania_select".
 */
export interface PresmerovaniaSelect<T extends boolean = true> {
  projekt?: T;
  zo?: T;
  na?: T;
  trvale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formulare_select".
 */
export interface FormulareSelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  slug?: T;
  polia?:
    | T
    | {
        popis?: T;
        kluc?: T;
        typ?: T;
        povinne?: T;
        napoveda?: T;
        moznosti?:
          | T
          | {
              hodnota?: T;
              id?: T;
            };
        id?: T;
      };
  textTlacidla?: T;
  spravaPoOdoslani?: T;
  presmerovanie?: T;
  prijemcovia?:
    | T
    | {
        email?: T;
        id?: T;
      };
  predmet?: T;
  potvrdenieOdosielatelovi?: T;
  textPotvrdenia?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "odpovede_select".
 */
export interface OdpovedeSelect<T extends boolean = true> {
  projekt?: T;
  formular?: T;
  suhrn?: T;
  udaje?: T;
  stav?: T;
  zdroj?: T;
  poznamka?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zaznamy_select".
 */
export interface ZaznamySelect<T extends boolean = true> {
  projekt?: T;
  akcia?: T;
  kolekcia?: T;
  nazov?: T;
  kto?: T;
  ktoPopis?: T;
  zaznamId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projekty_select".
 */
export interface ProjektySelect<T extends boolean = true> {
  nazov?: T;
  stav?: T;
  kod?: T;
  popis?: T;
  domenaHlavna?: T;
  domeny?:
    | T
    | {
        adresa?: T;
        id?: T;
      };
  verejneCitanie?: T;
  revalidateUrl?: T;
  revalidateSecret?: T;
  farba?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  meno?: T;
  master?: T;
  aktivny?: T;
  pristupy?:
    | T
    | {
        projekt?: T;
        rola?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-klienti_select".
 */
export interface ApiKlientiSelect<T extends boolean = true> {
  projekt?: T;
  nazov?: T;
  aktivny?: T;
  poznamka?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'stranky';
          value: number | Stranky;
        } | null)
      | ({
          relationTo: 'prispevky';
          value: number | Prispevky;
        } | null)
      | ({
          relationTo: 'udalosti';
          value: number | Udalosti;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}